# From https://github.com/patrickloeber/python-github-action-template
name: Run main.py

on:
  schedule:
    - cron: '35 17 * * 0-4' # At UTC-3 14:35 on every day-of-week from Sunday through Thursday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # install the python version needed
          
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install Playwright Firefox with dependencies
        run: playwright install firefox --with-deps

      - name: Execute Python script # run main.py
        env:
          URLS: ${{ secrets.URLS }}
          USER: ${{ secrets.USER }}
        run: python main.py
          
      # - name: commit files
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add -A
      #     git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      # - name: push changes
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: main 
